import Header from './components/Header'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Chase Rates Cars',
  description: 'Generated by the unrelenting genuis of Chase',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className='App'>
        <main>
          <nav>
            <Header />
          </nav>
          {children}
        </main>        
      </body>
    </html>
  )
}
